[package]
name = "microbit-rust"
version = "0.1.0"
authors = ["Ihsahn <ihsahn@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2"
microbit="0.8.0"
cortex-m-rt="0.6.12"

